apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-application-cont2
          image: 626316234718.dkr.ecr.ap-south-1.amazonaws.com/astion-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
