kind: Service
apiVersion: v1
metadata:
  name: frontend-application-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
